USE transaction;

CREATE TABLE transaction
(
    ID INT  NOT NULL AUTO_INCREMENT,
    TRANSACTION_ID VARCHAR(20)  NOT NULL,
    AMOUNT FLOAT  NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);